const userController = require('../controllers/userController');
const userMiddlewares = require('../middlewares/userMiddlewares');
const { user } = require('../config/multer');
const multer = require('multer')(user);
const router = require('express').Router();
router.get('/users', userController.index);
router.get('/user', userMiddlewares.authorization, userController.show);
router.post('/user', multer.single('user-photo'), userController.create);
router.post('/user/auth', userController.auth);
router.put('/user', userMiddlewares.authorization, multer.single('user-photo'), userController.update);
router.delete('/user', userMiddlewares.authorization, userController.delete);
module.exports = router;