const Sequelize = require('sequelize');
const dbconfig = require('../config/database');
const connection = new Sequelize(dbconfig);
const User = require('../models/User');
const Image = require('../models/Image');
const Gender = require('../models/Gender');
const Course = require('../models/Course');
const UserCourse = require('../models/UserCourse');
const Thumbnail = require('../models/Thumbnail');
User.init(connection);
Course.init(connection);
UserCourse.init(connection);
Image.init(connection);
Gender.init(connection);
Thumbnail.init(connection);
User.associate(connection.models);
Course.associate(connection.models);
Image.associate(connection.models);
Gender.associate(connection.models);
Thumbnail.associate(connection.models);
module.exports = connection;